apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: federation-gateway
spec:
  selector:
    # istio: ingressgateway -- must match Istio's ingressgateway service
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "idp.local"
    - "sp.local"
