apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
spec:
  replicas: {{ .Values.ldap.replicas }}
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
      - name: ldap
        image: {{ .Values.ldap.image }}
        ports:
        - containerPort: 389
