services:
  idp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shibboleth-idp
    ports:
      - "8080:8080"
    volumes:
      - ./conf/idp.properties:/opt/shibboleth-idp/conf/idp.properties
      - ./conf/access-control.xml:/opt/shibboleth-idp/conf/access-control.xml
      - ./conf/attribute-resolver.xml:/opt/shibboleth-idp/conf/attribute-resolver.xml
      - ./conf/ldap.properties:/opt/shibboleth-idp/conf/ldap.properties
      - ./certs:/opt/shibboleth-idp/certs:ro
